language: ruby
dist: precise
rvm:
  - "2.3.1"
install:
  - ". shell-scripts/install.sh"
branches:
  only:
    - "master"
    - "development"
    - "travis-testing"
script: ". shell-scripts/test.sh"
after_success: ". shell-scripts/final.sh"
